config/routes.rb
Rails.application.routes.draw do

  root 'workouts#home'

  get 'help' => 'workouts#help'
  get 'workouts' => 'workouts#workout_type'
  get 'signup' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def index

    end
    def create
      @user = User.from_auth( request.env["omniauth.auth"])
  #keeps me from having to authenticating each time
    session[:user_id] = @user.id
      redirect_to "/"
    end
    def destroy
      session.clear
      redirect_to "/"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def home
  end

  def help
  end

  def workout_type
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Fit Dual by Michael Kendall

  </small>
  <nav>
    <ul>
      <li><%= link_to "Exercises", '#' %><li>
        <li><%= link_to "Workouts", '#' %><li>
        <li><%= link_to "Contact", '#' %></li>
      </ul>
    </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Fit Dual", root_path, id: "logo" %>
    <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home",  root_path %></li>
      <li><%= link_to "Help",  help_path %></li>
      <li><%= link_to "Sign up", signup_path %></li>
    </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Fit Dual the Ultimate Fitness Challenge</title>
  <%= stylesheet_link_tag    'application', media: 'all',
                                            'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a sign-up page for new users.</p>

app/views/workouts/help.html.erb
<% provide(:title, "Help")%>
<h1>Workouts#help</h1>
<p>This would be where videos etc are.</p>

app/views/workouts/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Fit Dual the Ultimate Fitness Challenge</h1>

  <h2>
    This is the home page for
    <a href="https://www.fitbit.com/login">FitBit</a>
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"%>

</div>

app/views/workouts/workout_type.html.erb
<% provide(:title, "Workout Type")%>
<h1>Workout Type</h1>
<p> Listed are the type of workouts. </p>